name: Deploy to AWS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push frontend image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        echo "Current directory:"
        pwd
        echo "Directory contents:"
        ls -la
        echo "Frontend directory contents:"
        ls -la frontend/
        
        cd frontend
        docker build -t $ECR_REGISTRY/recipe-frontend:$IMAGE_TAG .

    - name: Deploy Frontend to App Runner
      run: |
        aws apprunner update-service \
          --service-arn ${{ secrets.APPRUNNER_SERVICE_ARN }} \
          --source-configuration '{"AutoDeploymentsEnabled":true,"ImageRepository":{"ImageIdentifier":"${{ steps.login-ecr.outputs.registry }}/recipe-frontend:${{ github.sha }}","ImageRepositoryType":"ECR","ImageConfiguration":{"Port":"80","RuntimeEnvironmentVariables":{"VITE_API_URL":"https://inkqxdx9em.ap-southeast-1.awsapprunner.com"}}}}'

    - name: Build and push backend image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      working-directory: ./backend
      run: |
        docker build -t $ECR_REGISTRY/recipe-backend:$IMAGE_TAG .
        docker tag $ECR_REGISTRY/recipe-backend:$IMAGE_TAG $ECR_REGISTRY/recipe-backend:latest
        docker push $ECR_REGISTRY/recipe-backend:$IMAGE_TAG
        docker push $ECR_REGISTRY/recipe-backend:latest

    - name: Deploy Backend to App Runner
      run: |
        aws apprunner update-service \
          --service-arn ${{ secrets.BACKEND_APPRUNNER_SERVICE_ARN }} \
          --source-configuration imageRepository="{imageIdentifier=${{ steps.login-ecr.outputs.registry }}/recipe-backend:${{ github.sha }},imageRepositoryType=ECR}"