name: Frontend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy to AWS Amplify
        run: |
          curl -sL https://aws-amplify.github.io/amplify-cli/install | bash && $SHELL
          amplify init --amplify "{\"envName\":\"prod\"}" --yes
          amplify add hosting --amplify "{\"appId\":\"d2sq26elbr7mze\"}" --yes
          amplify publish --yes