name: Frontend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
    
    - name: Build
      working-directory: ./frontend
      run: |
        npm ci
        echo "VITE_API_URL=https://fbwlfpmt9qd.ap-south-1.awsapprunner.com" >> .env
        npm run build
        
    - name: Deploy to Amplify
      env:
        AMPLIFY_APP_ID: d2sq26elbr7mze
      run: |
        aws amplify start-deployment --app-id $AMPLIFY_APP_ID --branch-name main --source-url ./frontend/dist