name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install and Build Frontend
      run: |
        cd Recipe-Creator
        npm ci
        npm run build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to AWS
      if: github.ref == 'refs/heads/main'
      run: |
        # Frontend deployment
        aws s3 sync Recipe-Creator/dist s3://aws-s3-bucket-recipe --delete
        
        # Backend deployment
        cd Recipe-Creator
        zip -r ../deploy.zip . -x "node_modules/*" "*.pyc" "__pycache__/*"
        
        # Upload to S3
        aws s3 cp ../deploy.zip s3://aws-s3-bucket-recipe/backend/deploy.zip --acl bucket-owner-full-control
        
        # Create/update EB application
        aws elasticbeanstalk create-application-version \
          --application-name recipe-creator \
          --version-label "v1-${{ github.sha }}" \
          --source-bundle S3Bucket=aws-s3-bucket-recipe,S3Key=backend/deploy.zip \
          --auto-create-application

        aws elasticbeanstalk update-environment \
          --application-name recipe-creator \
          --environment-name recipe-creator-env \
          --version-label "v1-${{ github.sha }}"