- name: Deploy to AWS
      if: github.ref == 'refs/heads/main'
      run: |
        # Frontend deployment
        aws s3 sync frontend/dist s3://aws-s3-bucket-recipe --delete
        
        # Backend deployment
        cd image_to_recipe
        zip -r ../deploy.zip . -x "node_modules/*" "*.pyc" "__pycache__/*"
        cd ..
        
        aws s3api put-object \
          --bucket aws-s3-bucket-recipe \
          --key deploy.zip \
          --body deploy.zip
        
        aws elasticbeanstalk create-application-version \
          --application-name recipe-creator \
          --version-label "v1-${{ github.sha }}" \
          --source-bundle S3Bucket=aws-s3-bucket-recipe,S3Key=deploy.zip
        
        aws elasticbeanstalk update-environment \
          --application-name recipe-creator \
          --environment-name recipe-creator-env \
          --version-label "v1-${{ github.sha }}"