name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install and Build Frontend
      run: |
        cd frontend
        npm install
        npm run build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to AWS
      if: github.ref == 'refs/heads/main'
      run: |
        # Frontend deployment
        aws s3 sync frontend/dist s3://aws-s3-bucket-recipe --delete
        
        # Backend deployment
        cd image_to_recipe
        zip -r ../deploy.zip . -x "node_modules/*" "*.pyc" "__pycache__/*"
        cd ..
        
        # Upload to S3 with versioned key
        VERSION_LABEL="v1-${{ github.sha }}"
        aws s3api put-object \
          --bucket aws-s3-bucket-recipe \
          --key "backend/$VERSION_LABEL/deploy.zip" \
          --body deploy.zip
        
        # Create EB version
        aws elasticbeanstalk create-application-version \
          --application-name recipe-creator \
          --version-label "$VERSION_LABEL" \
          --source-bundle S3Bucket="aws-s3-bucket-recipe",S3Key="backend/$VERSION_LABEL/deploy.zip"
        
        # Update environment
        aws elasticbeanstalk update-environment \
          --application-name recipe-creator \
          --environment-name recipe-creator-env \
          --version-label "$VERSION_LABEL"